# Numpy

In [ ]:
#Numpy is a Python library. Numpy is Numerical Python.
#It is a library consisting of multi-dimensional arrays.
#It allows only one datatype
#It doesn't have builtin functions
#Import numpy library for numerical python
#Numpy is faster than list
#pip install numpy-package installation


In [68]:
!pip install numpy
import numpy as np


In [12]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [13]:
a.ndim

1

In [14]:
a.shape

(6,)

In [15]:
b=np.arange(1,20,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
a=np.array(10)
b=np.array([2,2,2,2])
c=np.array([[45,45,67],[67,89,87]])
print(a)
print('\n')
print(b)
print('\n')
print(c)

10


[2 2 2 2]


[[45 45 67]
 [67 89 87]]


In [31]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


In [27]:
d=np.array([[[45,45,67],[67,89,87]],[[45,45,67],[67,89,87]]])
d

array([[[45, 45, 67],
        [67, 89, 87]],

       [[45, 45, 67],
        [67, 89, 87]]])

In [28]:
d.ndim

3

In [43]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [51]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
np.ones((5,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
np.full((6,4), 9,dtype=int)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [56]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [58]:
np.full((4,3),2,dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [59]:
A=[11,22,33,44,55,66]
np.diag(A)

array([[11,  0,  0,  0,  0,  0],
       [ 0, 22,  0,  0,  0,  0],
       [ 0,  0, 33,  0,  0,  0],
       [ 0,  0,  0, 44,  0,  0],
       [ 0,  0,  0,  0, 55,  0],
       [ 0,  0,  0,  0,  0, 66]])

# RESHAPE

In [76]:
N=[1,2,3,4,5,6,7,8,9,6,6,5,4,3,2]
N1=np.array(N)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 6, 5, 4, 3, 2])

In [71]:
np.ndim(N)

1

In [81]:
N2=N1.reshape((5,3))
N2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 6, 5],
       [4, 3, 2]])

In [80]:
import numpy as np
N = [1,2,3,4,5,6,7,8,9,6,6,5,4,3,2]
N_array = np.array(N)
N1 = N_array.reshape((5, 3))
N1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [6, 6, 5],
       [4, 3, 2]])

In [82]:
x=np.arange(2,20,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
R=np.array(x)
R

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [86]:
y=R.reshape(3,3)
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [88]:
y.shape

(3, 3)

In [89]:
y.ndim

2

In [94]:
x=np.arange(1,17)
print(x)
print(x.shape)
print(x.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1


In [95]:
r=x.reshape(8,2)
print(r)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [97]:
r=x.reshape(2,8)
print(r)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [98]:
r=x.reshape(4,4)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [99]:
r=x.reshape(16,1)
print(r)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [100]:
r=x.reshape(4,4,1)
print(r)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]]


In [101]:
r=x.reshape(8,2,1)
print(r)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]]


In [103]:
r.ndim

3

# Ravel

In [104]:
#ravel:undo the reshape
x.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [105]:
r=x.reshape(8,2,1)
print(r)

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]

 [[11]
  [12]]

 [[13]
  [14]]

 [[15]
  [16]]]


# flatten

In [106]:
#converts to 1 dimension -flatten
x.flatten()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [108]:
E=[12,12,13,14,15,16,17,18,19,20]
E1=np.array(E)
print(E1)

[12 12 13 14 15 16 17 18 19 20]


In [111]:
V=E1.reshape(5,2,1)
V

array([[[12],
        [12]],

       [[13],
        [14]],

       [[15],
        [16]],

       [[17],
        [18]],

       [[19],
        [20]]])

In [116]:
print(V[2][1][0])

16


In [117]:
a=[1,2,3,4,5,6,7,8,9]
a1=np.array(a)
a1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a1>4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [120]:
a1[a1>4]

array([5, 6, 7, 8, 9])

# Transpose
a1.transpose()

In [124]:
S=a1.reshape(3,3)
S

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
S.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Copy and View


In [ ]:
# The main difference between copy and view is that the copy is a new array and the view is just a view of the original array
#The copy owns the data and does not affect any changes made to the original data when any change is made to the copy 
#The view does not own the data and will affect the originat data when any changes are made to the view

In [127]:
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# View

In [128]:
#view
#Any changes made to the original data will affect the view and vice versa
x2=x1

In [129]:
print(x1)
print(x2)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [130]:
#now
x2[0]=10

In [131]:
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [132]:
print(id(x1))
print(id(x2))

2236077681584
2236077681584


In [133]:
#check whether they shares the same memory
np.shares_memory(x1,x2)

True

In [134]:
#create a view of x1 and store it in x3
x3=x1.view()
x3

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [135]:
np.shares_memory(x1,x3)

True

In [136]:
#change 1st element x3=100
x3[0]=100
x3

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [137]:
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


# COPY

In [138]:
#now create an array x4 which is a copy of x1
#ANy changes made to the original array will not affect the copy
x4=np.copy(x1)
x4

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [140]:
x4[-1]=900

In [143]:
print(id(x1))
print(id(x4))

2236077681584
2236076280304


In [142]:
np.shares_memory(x1,x4)

False

In [141]:
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]



# hstack and vstack funtion

In [ ]:
#Numpy provides a helper function
#Hstack :to stack along the rows 
#Vstack:tostack along the columns
#Stacking=concat

In [146]:
#Vstack ----along columns
print(x1)
print(x4)
np.vstack((x1,x4))


[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [147]:
#hstack ----along rows
print(x1)
print(x4)
np.hstack((x1,x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

# Insert,add,delete

In [148]:
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [149]:
#insert
np.insert(x1,4,x4)

array([100,   1,   2,   3, 100,   1,   2,   3,   4,   5,   6,   7,   8,
       900,   4,   5,   6,   7,   8,   9])

In [150]:
#delete
print(x2)
np.delete(x2,0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
#add
np.add(x2,111)

array([211, 112, 113, 114, 115, 116, 117, 118, 119, 120])

# Mathematical operations on numpy

In [154]:
import numpy as np
#defining a
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [155]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [157]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [160]:
Z=(np.sin(a))/(np.cos(a))
Z

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [161]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [162]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [163]:
#Print sum of elements in a
np.sum(a)


45

In [164]:
#print sum in array a columnwise
np.sum(a,axis=1)

array([ 6, 15, 24])

In [165]:
#print sum in array a rowwise
np.sum(a,axis=0)

array([12, 15, 18])

# Statistics

In [166]:
np.mean(a)

5.0

In [167]:
np.median(a)

5.0

In [170]:
np.std(a)

2.581988897471611

In [172]:
c=np.where(a==1)
c

(array([0], dtype=int64), array([0], dtype=int64))

In [176]:
d=[20,40,35,60,50,98]
d1=np.array(d)
d1

array([20, 40, 35, 60, 50, 98])

In [179]:
#provides the index for those numbers which gives remainder 0 when divided by 2

d2=np.where(d1%2==0)
d2

(array([0, 1, 3, 4, 5], dtype=int64),)

In [180]:
np.where (d1>50 ,d1,0)

array([ 0,  0,  0, 60,  0, 98])

In [181]:
np.where (d1>50)

(array([3, 5], dtype=int64),)

In [183]:
#to know how many methods are there 
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


In [184]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [185]:
print(dir(dict))

['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__ror__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


In [186]:
print(dir(tuple))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'count', 'index']


In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [21]:
import numpy as np
b=np.array([[(1,2,3,4),(5,6,7,8)]])
print(b)
print(type(b))
b.ndim

[[[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>


3

In [14]:
import numpy as np
c=np.array([[['a','b','c','d'],['e','f','g','h'],['i','j','k','l']]])
print(c)

[[['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'k' 'l']]]


In [20]:

array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)
array_3d[0,1,1]
array_3d.ndim

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [31]:
import numpy as np

c = np.array([[[ 'a', 'b', 'c', 'd'], 
               [ 'e', 'f', 'g', 'h'], 
               [ 'i', 'j', 'k', 'l']]])
print(c)
c.ndim
c[0,1,1]

[[['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'k' 'l']]]


'f'

In [27]:

D2_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(D2_array)

D2_array[1,1]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [32]:
D2_array.shape

(3, 3)

In [33]:
D2_array.dtype

dtype('int32')

In [34]:
D2_array.ndim

2

In [35]:
D2_array.itemsize

4

In [36]:
D2_array.nbytes

36

In [7]:
import numpy as np

e=np.array(3)
e.ndim


0

In [8]:
# 1 dimension
D=np.array([1,2,3,4])
D
D.ndim

1

In [9]:
#2 dimension
T=np.array([[2,3],[4,5]])
T.ndim

2

In [10]:
#3 dimension
R=np.array([[[1,2,3],[9,8,7],[4,5,6]]])
R.ndim

3

In [12]:
#Accesing Array elements:Indexing
#0th location
S=np.array([11,22,33,444])
S

array([ 11,  22,  33, 444])

In [13]:
S[1]

22

In [19]:
import numpy as np
F=np.array([[[23,34,35],[56,78,98]],[[12,33,44],[56,78,98]]])
F

array([[[23, 34, 35],
        [56, 78, 98]],

       [[12, 33, 44],
        [56, 78, 98]]])

In [20]:
F.ndim

3

In [21]:
C=np.array([[[23,34,35],[56,78,98]],[[12,33,44],[56,78,98]],[[45,67,88],[76,54,21]]])
C

array([[[23, 34, 35],
        [56, 78, 98]],

       [[12, 33, 44],
        [56, 78, 98]],

       [[45, 67, 88],
        [76, 54, 21]]])

In [22]:
C.ndim

3

In [24]:
C[0,1,1]

78

In [6]:
import numpy as np
R=np.array([[[23,34,35],[56,78,98],[22,44,55]],[[12,33,44],[56,78,98],[77,88,99]],[[45,67,88],[76,54,21],[74,68,90]],[[45,67,88],[76,54,21],[74,68,90]]])
R

array([[[23, 34, 35],
        [56, 78, 98],
        [22, 44, 55]],

       [[12, 33, 44],
        [56, 78, 98],
        [77, 88, 99]],

       [[45, 67, 88],
        [76, 54, 21],
        [74, 68, 90]],

       [[45, 67, 88],
        [76, 54, 21],
        [74, 68, 90]]])

In [7]:
R.ndim

3

In [8]:
R[1,1,2]

98

In [9]:
R.shape

(4, 3, 3)

In [19]:
import json 
json_obj='{"Name": "Sneha","Age":25,"Gender":"Femalle"}'
python_obj=json.loads(json_obj)
print('json_data:')
print(python_obj)
print('Name:',python_obj['Name'])
print('Age:',python_obj['Age'])
print('Gender:',python_obj['Gender'])


json_data:
{'Name': 'Sneha', 'Age': 25, 'Gender': 'Femalle'}
Name: Sneha
Age: 25
Gender: Femalle
