In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
a.ndim

1

In [6]:
a.shape

(3,)

In [21]:
import numpy as np
b=np.array([[(1,2,3,4),(5,6,7,8)]])
print(b)
print(type(b))
b.ndim

[[[1 2 3 4]
  [5 6 7 8]]]
<class 'numpy.ndarray'>


3

In [14]:
import numpy as np
c=np.array([[['a','b','c','d'],['e','f','g','h'],['i','j','k','l']]])
print(c)

[[['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'k' 'l']]]


In [20]:

array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)
array_3d[0,1,1]
array_3d.ndim

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [31]:
import numpy as np

c = np.array([[[ 'a', 'b', 'c', 'd'], 
               [ 'e', 'f', 'g', 'h'], 
               [ 'i', 'j', 'k', 'l']]])
print(c)
c.ndim
c[0,1,1]

[[['a' 'b' 'c' 'd']
  ['e' 'f' 'g' 'h']
  ['i' 'j' 'k' 'l']]]


'f'

In [27]:

D2_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
print(D2_array)

D2_array[1,1]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [32]:
D2_array.shape

(3, 3)

In [33]:
D2_array.dtype

dtype('int32')

In [34]:
D2_array.ndim

2

In [35]:
D2_array.itemsize

4

In [36]:
D2_array.nbytes

36

In [7]:
import numpy as np

e=np.array(3)
e.ndim


0

In [8]:
# 1 dimension
D=np.array([1,2,3,4])
D
D.ndim

1

In [9]:
#2 dimension
T=np.array([[2,3],[4,5]])
T.ndim

2

In [10]:
#3 dimension
R=np.array([[[1,2,3],[9,8,7],[4,5,6]]])
R.ndim

3

In [12]:
#Accesing Array elements:Indexing
#0th location
S=np.array([11,22,33,444])
S

array([ 11,  22,  33, 444])

In [13]:
S[1]

22

In [19]:
import numpy as np
F=np.array([[[23,34,35],[56,78,98]],[[12,33,44],[56,78,98]]])
F

array([[[23, 34, 35],
        [56, 78, 98]],

       [[12, 33, 44],
        [56, 78, 98]]])

In [20]:
F.ndim

3

In [21]:
C=np.array([[[23,34,35],[56,78,98]],[[12,33,44],[56,78,98]],[[45,67,88],[76,54,21]]])
C

array([[[23, 34, 35],
        [56, 78, 98]],

       [[12, 33, 44],
        [56, 78, 98]],

       [[45, 67, 88],
        [76, 54, 21]]])

In [22]:
C.ndim

3

In [24]:
C[0,1,1]

78

In [6]:
import numpy as np
R=np.array([[[23,34,35],[56,78,98],[22,44,55]],[[12,33,44],[56,78,98],[77,88,99]],[[45,67,88],[76,54,21],[74,68,90]],[[45,67,88],[76,54,21],[74,68,90]]])
R

array([[[23, 34, 35],
        [56, 78, 98],
        [22, 44, 55]],

       [[12, 33, 44],
        [56, 78, 98],
        [77, 88, 99]],

       [[45, 67, 88],
        [76, 54, 21],
        [74, 68, 90]],

       [[45, 67, 88],
        [76, 54, 21],
        [74, 68, 90]]])

In [7]:
R.ndim

3

In [8]:
R[1,1,2]

98

In [9]:
R.shape

(4, 3, 3)

In [19]:
import json 
json_obj='{"Name": "Sneha","Age":25,"Gender":"Femalle"}'
python_obj=json.loads(json_obj)
print('json_data:')
print(python_obj)
print('Name:',python_obj['Name'])
print('Age:',python_obj['Age'])
print('Gender:',python_obj['Gender'])


json_data:
{'Name': 'Sneha', 'Age': 25, 'Gender': 'Femalle'}
Name: Sneha
Age: 25
Gender: Femalle
